# Generated by Django 5.1 on 2024-09-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_city_options_alter_province_options_and_more'),
        ('shop', '0002_alter_product_off_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='saved_products',
            field=models.ManyToManyField(related_name='saved_users', to='shop.product', verbose_name='محصولات ذخیره شده'),
        ),
    ]
