# Generated by Django 5.1 on 2024-09-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_shopuser_saved_products'),
        ('shop', '0003_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='saved_products',
            field=models.ManyToManyField(related_name='saved_by', to='shop.product', verbose_name='محصولات ذخیره شده: '),
        ),
    ]
