# Generated by Django 5.1 on 2024-09-24 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_shopuser_saved_products'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='shop_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='shop_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='ShopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن مالک')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل مالک')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام مالک')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی مالک')),
                ('shop_name', models.CharField(max_length=100, verbose_name='نام فروشگاه')),
                ('shop_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل فروشگاه')),
                ('shop_phone', models.CharField(max_length=100, unique=True, verbose_name='شماره تلفن فروشگاه')),
                ('shop_address', models.CharField(max_length=100, verbose_name='آدرس فروشگاه')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='shop_seller_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='shop_seller_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
