# Generated by Django 5.1 on 2026-08-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_shopuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopseller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
