# Generated by Django 5.1 on 2026-08-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_shopseller_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopseller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='لوگو'),
        ),
    ]
