# Generated by Django 5.1 on 2026-08-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_shopseller_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='آدرس پیشفرض'),
        ),
    ]
