# Generated by Django 5.1 on 2024-09-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت پس از اعمال تخفیف'),
        ),
    ]
