# Generated by Django 5.1 on 2024-09-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_off_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='کد تخفثیف')),
                ('type', models.CharField(choices=[('روی مبلغ نهایی (درصد)', 'روی مبلغ نهایی (درصد)'), ('روی مبلغ نهایی (مبلغ)', 'روی مبلغ نهایی (مبلغ)'), ('روی هزینه ارسال (درصد)', 'روی هزینه ارسال (درصد)')], max_length=250, verbose_name='نوع')),
                ('value', models.PositiveIntegerField(verbose_name='مبلغ یا درصد تخفیف')),
            ],
        ),
    ]
