# Generated by Django 5.1 on 2025-01-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_image_image_file_alter_productfeature_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='وضعیت موجودی'),
        ),
    ]
