# Generated by Django 5.1 on 2025-02-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_color_option',
            field=models.BooleanField(default=False, verbose_name='رنگ بندی دارد؟'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_size_option',
            field=models.BooleanField(default=False, verbose_name='سایزبندی دارد؟'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='موجود می باشد'),
        ),
        migrations.CreateModel(
            name='ProductColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='اندازه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='shop.product')),
            ],
        ),
    ]
