# Generated by Django 5.1 on 2025-02-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productvariant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_variant',
        ),
    ]
