# Generated by Django 5.1 on 2026-08-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productvariant_unique_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_file',
            field=models.ImageField(default='Null', upload_to='images/%Y/%m/%d', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
