# Generated by Django 5.1 on 2026-08-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_category_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_sale_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='پایان شگفت انگیز'),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع شگفت انگیز'),
        ),
    ]
