# Generated by Django 5.1 on 2026-08-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
