# Generated by Django 5.1 on 2026-08-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_brand_sales_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروش'),
        ),
    ]
