# Generated by Django 5.1 on 2026-08-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_shopseller_logo'),
        ('shop', '0015_alter_brand_sales_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت فروشنده')),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name='موجودی فروشنده')),
                ('warranty', models.CharField(blank=True, max_length=100, null=True, verbose_name='گارانتی')),
                ('satisfaction', models.PositiveIntegerField(default=0, verbose_name='رضایت مشتری')),
                ('performance', models.CharField(default='عالی', max_length=50, verbose_name='عملکرد')),
                ('shipping_type', models.CharField(default='ارسال شاپیک', max_length=100, verbose_name='نوع ارسال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='shop.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_products', to='account.shopseller')),
            ],
            options={
                'unique_together': {('product', 'seller')},
            },
        ),
    ]
