# Generated by Django 5.1 on 2026-08-07 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productseller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دیدگاه')),
                ('body', models.TextField(max_length=2000, verbose_name='متن دیدگاه')),
                ('score', models.PositiveIntegerField(default=5, verbose_name='امتیاز')),
                ('is_recommended', models.BooleanField(default=True, verbose_name='پیشنهاد می\u200cکنم')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='تعداد پسند')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='تعداد نپسند')),
                ('is_buyer', models.BooleanField(default=False, verbose_name='خریدار محصول')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('positive_points', models.TextField(blank=True, null=True, verbose_name='نکات مثبت')),
                ('negative_points', models.TextField(blank=True, null=True, verbose_name='نکات منفی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دیدگاه',
                'verbose_name_plural': 'دیدگاه\u200cها',
                'ordering': ['-created'],
            },
        ),
    ]
