# Generated by Django 5.1 on 2026-08-07 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_seller_productcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={},
        ),
        migrations.AddConstraint(
            model_name='productcomment',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_comment'),
        ),
    ]
