# Generated by Django 5.1 on 2026-08-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_productcomment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'موضوع دیدگاه',
                'verbose_name_plural': 'موضوعات دیدگاه',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ['-created'], 'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاه\u200cها'},
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='negative_points',
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='positive_points',
        ),
        migrations.CreateModel(
            name='ProductCommentPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('positive', 'مثبت'), ('negative', 'منفی')], max_length=10, verbose_name='نوع')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_points', to='shop.productcomment', verbose_name='دیدگاه')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_relations', to='shop.commentpoint', verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'موضوع دیدگاه محصول',
                'verbose_name_plural': 'موضوعات دیدگاه محصول',
            },
        ),
        migrations.AddField(
            model_name='productcomment',
            name='points',
            field=models.ManyToManyField(blank=True, related_name='comments', through='shop.ProductCommentPoint', to='shop.commentpoint', verbose_name='موضوعات دیدگاه'),
        ),
        migrations.AddConstraint(
            model_name='productcommentpoint',
            constraint=models.UniqueConstraint(fields=('comment', 'point'), name='unique_comment_point'),
        ),
    ]
