# Generated by Django 5.1 on 2026-08-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_commentpoint_alter_productcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentpoint',
            options={'verbose_name': 'موضوع کامنت', 'verbose_name_plural': 'موضوعات کامنت'},
        ),
        migrations.RemoveField(
            model_name='commentpoint',
            name='name',
        ),
        migrations.AddField(
            model_name='commentpoint',
            name='title',
            field=models.CharField(default='None', max_length=100, verbose_name='موضوع'),
            preserve_default=False,
        ),
    ]
