# Generated by Django 5.1 on 2026-08-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_commentpoint_options_remove_commentpoint_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='negative_points',
            field=models.TextField(blank=True, null=True, verbose_name='نکات منفی'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='positive_points',
            field=models.TextField(blank=True, null=True, verbose_name='نکات مثبت'),
        ),
    ]
