# Generated by Django 5.1 on 2026-08-08 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_productcomment_negative_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommentpoint',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_points', to='shop.productcomment', verbose_name='دیدگاه'),
        ),
        migrations.AlterField(
            model_name='productcommentpoint',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_relations', to='shop.commentpoint', verbose_name='موضوع'),
        ),
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000, verbose_name='متن پرسش')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='تعداد پسند')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='تعداد نپسند')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='shop.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_questions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرسش محصول',
                'verbose_name_plural': 'پرسش\u200cهای محصول',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1500, verbose_name='متن پاسخ')),
                ('is_seller', models.BooleanField(default=False, verbose_name='پاسخ فروشنده')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_answers', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='shop.productquestion', verbose_name='پرسش')),
            ],
            options={
                'verbose_name': 'پاسخ پرسش',
                'verbose_name_plural': 'پاسخ\u200cهای پرسش',
                'ordering': ['created'],
            },
        ),
    ]
