# Generated by Django 5.1 on 2026-08-16 17:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_searchquery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('view', 'مشاهده'), ('wishlist', 'علاقه\u200cمندی'), ('cart', 'افزودن به سبد'), ('purchase', 'خرید')], max_length=20, verbose_name='نوع تعامل')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان تعامل')),
                ('dwell_time', models.PositiveIntegerField(default=0, verbose_name='مدت زمان مشاهده (ثانیه)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='shop.product', verbose_name='محصول')),
                ('search_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='shop.searchquery', verbose_name='جستجوی مبدا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تعامل',
                'verbose_name_plural': 'تعاملات',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='shop_intera_user_id_f81d5d_idx'), models.Index(fields=['product', 'event'], name='shop_intera_product_f010aa_idx'), models.Index(fields=['search_query'], name='shop_intera_search__5a875c_idx')],
            },
        ),
    ]
