# Generated by Django 5.1 on 2026-08-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='source',
            field=models.CharField(default='direct', max_length=50),
        ),
    ]
