# Generated by Django 5.1 on 2026-08-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_interaction_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='dwell_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مدت زمان مشاهده (ثانیه)'),
        ),
    ]
