# Generated by Django 5.1 on 2026-08-16 20:27

import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_interaction_dwell_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='interaction',
            name='shop_intera_search__5a875c_idx',
        ),
        migrations.AddField(
            model_name='interaction',
            name='interaction_score',
            field=models.FloatField(default=1, verbose_name='امتیاز تعامل'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='شناسه نشست'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='dwell_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مدت مشاهده (ثانیه)'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='source',
            field=models.CharField(choices=[('search', 'جستجو'), ('home', 'صفحه اصلی'), ('category', 'دسته بندی'), ('direct', 'مستقیم')], default='direct', max_length=50, verbose_name='منبع تعامل'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان تعامل'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['session_id', 'timestamp'], name='shop_intera_session_e53b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['source'], name='shop_intera_source_590a92_idx'),
        ),
    ]
