# Generated by Django 5.1 on 2026-08-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_interaction_shop_intera_search__5a875c_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
