# Generated by Django 5.1 on 2026-08-17 16:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
        ('shop', '0027_remove_interaction_shop_intera_search__5a875c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='شناسه نشست')),
                ('source', models.CharField(choices=[('search', 'جستجو'), ('home', 'صفحه اصلی'), ('category', 'دسته بندی'), ('direct', 'مستقیم')], default='direct', max_length=50, verbose_name='منبع تعامل')),
                ('event', models.CharField(choices=[('view', 'مشاهده'), ('wishlist', 'علاقه\u200cمندی'), ('cart', 'افزودن به سبد'), ('purchase', 'خرید')], max_length=20, verbose_name='نوع تعامل')),
                ('interaction_score', models.FloatField(default=1, verbose_name='امتیاز تعامل')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان تعامل')),
                ('dwell_time', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مدت مشاهده (ثانیه)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_interactions', to='shop.product')),
                ('search_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_interactions', to='shop.searchquery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تعامل',
                'verbose_name_plural': 'تعاملات',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='recommendat_user_id_e2bb25_idx'), models.Index(fields=['session_id', 'timestamp'], name='recommendat_session_b950ce_idx'), models.Index(fields=['product', 'event'], name='recommendat_product_fc22d5_idx'), models.Index(fields=['source'], name='recommendat_source_220de7_idx')],
            },
        ),
    ]
