# Generated by Django 5.1 on 2026-08-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_interaction_delete_recommendationinteraction_and_more'),
        ('shop', '0028_delete_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='favorite_brands',
            field=models.ManyToManyField(blank=True, to='shop.brand'),
        ),
    ]
