# Generated by Django 5.1 on 2024-09-01 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('در صف بررسی', 'در صف بررسی'), ('تایید سفارش', 'تایید سفارش'), ('دریافت از فروشنده', 'دریافت از فروشنده'), ('آماده سازی سفارش', 'آماده سازی سفارش'), ('تحویل به پست', 'تحویل به پست'), ('تحویل مرسوله به مشتری', 'تحویل مرسوله به مشتری'), ('عودت هزینه به دلیل عدم موجودی', 'عودت هزینه به دلیل عدم موجودی')], default='در صف بررسی', max_length=100, verbose_name='وضعیت')),
                ('name', models.CharField(max_length=120, verbose_name='نام تحویل گیرنده')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.CharField(max_length=150, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن تحویل گیرنده')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت با موفقیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='وزن')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created'], name='order_order_created_ef2486_idx'),
        ),
    ]
