# Generated by Django 5.1 on 2024-09-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_city_remove_order_province'),
        ('shop', '0002_alter_product_off_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='مبلغ قابل بازگشت به خریدار')),
                ('accepted', models.BooleanField(default=False, verbose_name='پذیرش مرجوعی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_products', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد مرجوعی')),
                ('explanation', models.TextField(default='', verbose_name='توضیحات مرجوعی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='shop.product')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_products', to='order.returnorder')),
            ],
        ),
    ]
