# Generated by Django 5.1 on 2024-09-03 16:07

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_returnorder_returnproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnorder',
            options={'ordering': ['created'], 'verbose_name': 'سفارش مرجوعی', 'verbose_name_plural': 'سفارشات مرجوعی'},
        ),
        migrations.AddField(
            model_name='returnorder',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
    ]
