# Generated by Django 5.1 on 2024-09-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_returnorder_options_returnorder_created'),
        ('shop', '0002_alter_product_off_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_products', to='shop.image'),
        ),
    ]
