# Generated by Django 5.1 on 2024-09-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_returnproduct_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproduct',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
