# Generated by Django 5.1 on 2024-09-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_returnproduct_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproduct',
            name='photo',
            field=models.ImageField(upload_to='return_products/', verbose_name='تصویر کالای مرجوعی'),
        ),
    ]
