# Generated by Django 5.1 on 2024-09-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_returnproduct_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='cost',
            field=models.CharField(default='', max_length=7, verbose_name='مبلغ قابل بازگشت به خریدار'),
        ),
    ]
