# Generated by Django 5.1 on 2024-09-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_returnorder_cost'),
        ('shop', '0003_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.discountcode', verbose_name='کد تخفیف اعمال شده'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ قابل پرداخت نهایی (با احتساب کد تخفیف)'),
        ),
    ]
