# Generated by Django 5.1 on 2024-09-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_discount_code_order_final_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل مرسوله به مشتری'),
        ),
    ]
