# Generated by Django 5.1 on 2025-03-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='اندازه'),
        ),
    ]
