# Generated by Django 5.1 on 2026-08-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('در صف بررسی', 'در صف بررسی'), ('تایید سفارش', 'تایید سفارش'), ('دریافت از فروشنده', 'دریافت از فروشنده'), ('آماده سازی سفارش', 'آماده سازی سفارش'), ('تحویل به پست', 'تحویل به پست'), ('تحویل مرسوله به مشتری', 'تحویل مرسوله به مشتری'), ('عودت هزینه به دلیل عدم موجودی', 'عودت هزینه به دلیل عدم موجودی'), ('لغو شده', 'لغو شده')], default='در صف بررسی', max_length=100, verbose_name='وضعیت'),
        ),
    ]
